#!/bin/bash
if [[ "$INITSYSTEM" == "on" ]]; then
	DBUS_SYSTEM_BUS_ADDRESS=unix:path=/host_run/dbus/system_bus_socket npm start
else
	npm start
fi

# Run the RF24Network server parsin messages from Nodes
./helloworld_rx > /data/logs/RF24Network/helloworld_rx.log

# We run the Python app after the wifi connection has been established
# and the previous command has exited.
cd ./python-server && python main.py

while true
do
	echo "App exited but container is still running to allow web terminal access"
	sleep 3600
done
