#!/bin/bash
# RF24 Compilation
cd ./RF24-$RF24_VERSION && sudo make install
# RF24Network Compilation
cd ../RF24Network-$RF24NETWORK_VERSION && sudo make install
# RF24Network Server Compilation
cd ../rf24network-server && make
chmod +x ./rf24network_rx
mkdir -p /data/logs/rf24network-server
touch /data/logs/rf24network-server/rf24network_rx.log
# Run the RF24Network Server Parsing messages from Nodes
./rf24network_rx > /data/logs/rf24network-server/rf24network_rx.log &

# Run Wifi Connect
if [[ "$INITSYSTEM" == "on" ]]; then
	DBUS_SYSTEM_BUS_ADDRESS=unix:path=/host_run/dbus/system_bus_socket npm start
else
	npm start
fi

# We run the Python app after the wifi connection has been established
# and the previous command has exited.
cd ../python-server && python main.py

while true
do
	echo "App exited but container is still running to allow web terminal access"
	sleep 3600
done
